Dictionary_monthly_pre_amz_best_method_statist_cmip5_models_1975-2005={
'pbias': ['MRI-CGCM3', 'HadGEM2-ES', 'CSIRO-ACCESS-3', 'CSIRO-ACCESS-3', 'CSIRO-ACCESS-3', 'MRI-CGCM3', 'HadGEM2-AO', 'HadGEM2-AO', 'HadGEM2-AO', 'CSIRO-ACCESS-3', 'NCAR-CESM1-BGC', 'MIROC'], 
'rmse': ['CSIRO-MK36', 'CSIRO-MK36', 'BCC-CSM1.1M', 'BCC-CSM1.1M', 'BCC-CSM1.1M', 'BCC-CSM1.1M', 'CSIRO-MK36', 'CSIRO-MK36', 'CSIRO-MK36', 'IPSL-CM5A-LR', 'IPSL-CM5A-MR', 'CanESM2'], 
'bias': ['MRI-CGCM3', 'HadGEM2-ES', 'CSIRO-ACCESS-3', 'CSIRO-ACCESS-3', 'CSIRO-ACCESS-3', 'MRI-CGCM3', 'HadGEM2-AO', 'HadGEM2-AO', 'HadGEM2-AO', 'CSIRO-ACCESS-3', 'NCAR-CESM1-BGC', 'MIROC'], 
'mae': ['MRI-CGCM3', 'HadGEM2-ES', 'CSIRO-ACCESS-3', 'CSIRO-ACCESS-3', 'CSIRO-ACCESS-3', 'MRI-CGCM3', 'HadGEM2-AO', 'HadGEM2-AO', 'HadGEM2-AO', 'CSIRO-ACCESS-3', 'NCAR-CESM1-BGC', 'MIROC'], 
'apb': ['NorESM1-M', 'NorESM1-M', 'NorESM1-M', 'NorESM1-M', 'NorESM1-M', 'NorESM1-M', 'NorESM1-M', 'NorESM1-M', 'NorESM1-M', 'NorESM1-M', 'NorESM1-M', 'NorESM1-M'], 
'r': ['NCAR-CCSM4', 'FIO-ESM', 'LASG-FGOALS-G2', 'MPI-ESM-MR', 'LASG-FGOALS-G2', 'MRI-CGCM3', 'HadGEM2-ES', 'GISS-E2-H', 'NCAR-CESM1-BGC', 'IPSL-CM5A-MR', 'LASG-FGOALS-S2', 'MPI-ESM-MR'], 
'effic': ['INMCM4', 'GISS-E2-R', 'INMCM4', 'GISS-E2-H', 'INMCM4', 'HadGEM2-ES', 'CSIRO-ACCESS-1', 'INMCM4', 'INMCM4', 'GISS-E2-H', 'LASG-FGOALS-G2', 'LASG-FGOALS-G2']}
