Dictionary_monthly_tmp_amz_best_method_statist_cmip5_models_1975-2005={
'pbias': ['CSIRO-MK36', 'CSIRO-MK36', 'BCC-CSM1.1M', 'BCC-CSM1.1M', 'BCC-CSM1.1M', 'BCC-CSM1.1M', 'CSIRO-MK36', 'CSIRO-MK36', 'CSIRO-MK36', 'CSIRO-MK36', 'CanESM2', 'CanESM2'], 
'rmse': ['INMCM4', 'CSIRO-MK36', 'INMCM4', 'INMCM4', 'INMCM4', 'INMCM4', 'INMCM4', 'INMCM4', 'CSIRO-MK36', 'CSIRO-MK36', 'CanESM2', 'CanESM2'], 
'bias': ['CSIRO-MK36', 'CSIRO-MK36', 'BCC-CSM1.1M', 'BCC-CSM1.1M', 'BCC-CSM1.1M', 'BCC-CSM1.1M', 'CSIRO-MK36', 'CSIRO-MK36', 'CSIRO-MK36', 'CSIRO-MK36', 'CanESM2', 'CanESM2'], 
'mae': ['CSIRO-MK36', 'CSIRO-MK36', 'BCC-CSM1.1M', 'BCC-CSM1.1M', 'BCC-CSM1.1M', 'BCC-CSM1.1M', 'CSIRO-MK36', 'CSIRO-MK36', 'CSIRO-MK36', 'CSIRO-MK36', 'CanESM2', 'CanESM2'], 
'apb': ['NorESM1-M', 'NorESM1-M', 'NorESM1-M', 'NorESM1-M', 'NorESM1-M', 'NorESM1-M', 'NorESM1-M', 'NorESM1-M', 'NorESM1-M', 'NorESM1-M', 'NorESM1-M', 'NorESM1-M'], 
'r': ['HadGEM2-AO', 'LASG-FGOALS-G2', 'LASG-FGOALS-G2', 'FIO-ESM', 'HadGEM2-AO', 'NCAR-CCSM4', 'IPSL-CM5A-LR', 'HadGEM2-ES', 'BCC-CSM1.1', 'FIO-ESM', 'MIROC-ESM', 'NorESM1-ME'], 
'effic': ['HadGEM2-AO', 'IPSL-CM5A-LR', 'HadGEM2-AO', 'HadGEM2-AO', 'BCC-CSM1.1', 'IPSL-CM5A-MR', 'IPSL-CM5A-MR', 'IPSL-CM5A-MR', 'IPSL-CM5A-MR', 'NCAR-CESM1-BGC', 'CSIRO-ACCESS-1', 'MIROC-ESM']}
